apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: gitops-kustomize
bases:
- ./eventBrokerSource
- ./jsonStorage
- ./eventBrokerSink
- ./postgres
# Create artifactory pull secret
secretGenerator:
  - name: artifactory-secret
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
configMapGenerator:
- name: solace-config
  literals:
  - host=solace-pubsubplus-openshift-dev
  - username=test
  - topic=test/topic

helmChartInflationGenerator:
- chartName: solace-pubsubplus-openshift-dev
  chartRepoUrl: https://charts.openshift.io/
  chartVersion: 3.1.0
  # releaseName: solace
  # override with these custom values
  # values: ./values-aro.yaml