apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: gitops-kustomize
#common labels to apply
# commonLabels:
#   app: configuration-logger
#   version: v1

#List of resource files that Kustomize reads, modifies and emits as a YAML string
resources:
- deployment.yaml
- route.yaml
- service.yaml
# Create artifactory pull secret
secretGenerator:
  - name: artifactory-secret
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
  - name: db-config-secret
    literals:
    - user=yuriy
    - name=eventdb
    - password=1234
# Creates a config map
configMapGenerator:
- name: db-configmap
  literals:
  - host=event-database
  - type=jdbc:postgresql
  - port=5432