apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-broker-service
  namespace: gitops-kustomize
spec:
  destination:
    namespace: gitops-kustomize
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: event-broker-source
    repoURL: https://github.com/danialasghar/GitOps-PoC.git
    targetRevision: main