apiVersion: v1
entries:
  eventBrokerSource:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-06T05:23:24.5887271Z"
    description: A Helm chart for Kubernetes
    digest: 04e9fe1c2397e8eaf9fd84b8599fbda6ff6594d305ea727a248acc092967a995
    name: eventBrokerSource
    type: application
    urls:
    - https://github.com/danialasghar/GitOps-PoC/tree/main/eventBrokerSource/eventBrokerSource-0.1.0.tgz
    version: 0.1.0
generated: "2023-02-06T05:23:24.585043Z"
