apiVersion: v1
entries:
  eventBrokerSource:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-06T18:22:48.9923895Z"
    description: A Helm chart for Kubernetes
    digest: 774177dfe3c61e95034fa445807d4918d0b4a595ac56588e69fd2e4d75443a90
    name: eventBrokerSource
    type: application
    urls:
    - - eventBrokerSource-0.1.0.tgz
    version: 0.1.0
generated: "2023-02-06T18:22:48.9917446Z"
