apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- deployment.yaml
- route.yaml
- service.yaml

configMapGenerator:
- name: storage-service-config
  literals:
  - url=http://json-storage:8080