---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: postgres-init
    options:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server 
    files:
      - configs/init.sql
  - name: postgres-server
    options:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server
    literals:
      - POSTGRES_DB=eventdb
secretGenerator:
  - name: postgres-creds
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server
    literals: 
    - POSTGRES_USER=yuriy
    - POSTGRES_PASSWORD=1234
  #   envs: 
  #     - user.env
  # - name: postgres-admin
  #   options:
  #     disableNameSuffixHash: true
  #     labels:
  #       app.kubernetes.io/name: postgres
  #       app.kubernetes.io/component: server
  #  literals:
  #  - POSTGRES_ADMIN=admin
  #  - POSTGRES_PASSWORD=admin
  #   envs: 
  #     - admin.env

images:
  - name: postgres-server
    newName: library/postgres
    newTag: "15"

...
