apiVersion: v1
kind: ConfigMap
metadata:
  name: solace-config
data:
  host: {{ .Values.solaceEventBroker.host | quote }}
  username: {{ .Values.solaceEventBroker.username | quote }}
  topic: {{ .Values.solaceEventBroker.topic | quote }}