apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: ""
    name: {{ .Values.name }}
    weight: null
status: {}
