# Default values for eventBrokerSource.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

solaceEventBroker:
  host: solace-pubsubplus-openshift-dev.gitops-helm.svc.cluster.local
  username: test
  topic: test/topic