# Default values for eventBrokerSource.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

solaceEventBroker:
  host: pubsubplus-openshift-cris-pubsubplus-openshift.gitops-kustomize.svc.cluster.local
  username: test
  topic: test/topic