apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pubsubplus-openshift-dev
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: argocd3
    server: 'https://kubernetes.default.svc'
  source:
    path: solace/helm/pubsubplus-openshift-dev
    repoURL: https://github.com/danialasghar/GitOps-PoC.git
    targetRevision: main
  project: default
