apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pubsubplus-openshift-dev
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: argocd3
    server: 'https://kubernetes.default.svc'
  source:
    chart: pubsubplus-openshift-dev
    repoURL: https://charts.openshift.io
    targetRevision: 3.0.0
  project: default
