apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: artifactory

commonLabels:
  test.label: Yuriy
  
helmChartInflationGenerator:
- chartName: artifactory
  chartRepoUrl: https://charts.jfrog.io/
  # override with these custom values
  values: ./values-aro.yaml