apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: gitops-kustomize

resources:
- deployment.yaml
- route.yaml
- service.yaml

secretGenerator:
  - name: artifactory-secret
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson

configMapGenerator:
- name: solace-config
  literals:
  - host=solace-pubsubplus-openshift-dev
  - username=test
  - topic=test/topic
- name: storage-service-config
  literals:
  - url=http://json-storage:8080

