# repositories:
#   - name: stable
#     url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: event-broker-source
    chart: ./eventBrokerSource
    values:
      - ./eventBrokerSource/values.yaml

  - name: solace
    chart: ./pubsubplus-openshift-dev
    values:
      - ./pubsubplus-openshift-dev/values.yaml
      
  # - name: kanban-app
  #   chart: ./charts/app
  #   values:
  #     - ./values/kanban-app.yaml
  
  # - name: kanban-ui
  #   chart: ./charts/app
  #   values:
  #     - ./values/kanban-ui.yaml

  # - name: ingress-backend
  #   chart: stable/nginx-ingress
  #   version: 1.36.0

  # - name: ingress-controller
  #   chart: ./charts/ingress
  #   values:
  #     - ./values/ingress.yaml