---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: postgres-init
    options:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server 
    files:
      - configs/user.sh
  - name: postgres-server
    options:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server
    literals:
      - POSTGRES_DB=postgres
      - POSTGRES_GENERAL_DATABASE=postgresdb
#      - POSTGRES_ADMIN=postgres
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_GENERAL_USERNAME=kaylaa
#      - POSTGRES_GENERAL_PASSWORD=passwd

secretGenerator:
  - name: postgres-user
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server
#    literals: 
#    - POSTGRES_GENERAL_USERNAME=Kayla
#    - POSTGRES_GENERAL_PASSWORD=passwd
    envs: 
      - user.env
  - name: postgres-admin
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: server
#    literals:
#    - POSTGRES_ADMIN=admin
#    - POSTGRES_PASSWORD=admin
    envs: 
      - admin.env

images:
  - name: postgres-server
    newName: library/postgres
    newTag: "15"

...
