apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-broker-poc-argocd-helm
spec:
  project: argocd
  source:
    path: eventBrokerPoc/helm-apps/
    repoURL: 'https://github.com/danialasghar/GitOps-PoC.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: argocd-helm
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true