apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-secret
data:
  user: {{ .Values.dbConfigSecret.user | quote }}
  name: {{ .Values.dbConfigSecret.name | quote }}
  password: {{ .Values.dbConfigSecret.password | quote }}
---
metadata:
  name: db-configmap
data:
  host: {{ .Values.dbConfig.host | quote }}
  type: {{ .Values.dbConfig.type | quote }}
  port: {{ .Values.dbConfig.port | quote }} 