apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: host
          - name: USERNAME
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: username
          - name: TOPIC
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: topic
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: storage-config
                key: url
          resources: {}
      
