replicaCount: 1
postgres:
  name: postgres
  namespace: gitops-helm
  group: db
  container:
    image: postgres:9.6-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: postgres-config
    data:
      - key: POSTGRES_DB
        value: test
      - key: POSTGRES_USER
        value: test
      - key: POSTGRES_PASSWORD
        value: test