replicaCount: 2
serviceAccount:
  enabled: true
  name: postgres-gitops-helm-deployment-admin
postgres:
  name: helm-postgres
  namespace: gitops-helm
  group: db
  container:
    image: postgres:15.1-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: helm-postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /postgresql/data
    pvc:
      name: helm-postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: helm-postgres-config
    data:
      - key: POSTGRES_DB
        value: test
      - key: POSTGRES_USER
        value: test
      - key: POSTGRES_PASSWORD
        value: test
