replicaCount: 1
serviceAccount:
  enabled: true
  name: postgres-gitops-helm-deployment-admin
postgres:
  name: postgres
  namespace: gitops-helm
  group: db
  container:
    image: postgres:15.1-alpine
    port: 5432
  service:
    type: ClusterIP
    port: 5432
  volume:
    name: third-postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: third-postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi
  config:
    name: third-postgres-config
    data:
      - key: POSTGRES_DB
        value: test
      - key: POSTGRES_USER
        value: test
      - key: POSTGRES_PASSWORD
        value: test
