NAME: poc
LAST DEPLOYED: Mon Feb  6 18:43:42 2023
NAMESPACE: hel-test
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
image:
  pullPolicy: IfNotPresent
  repository: artifactory-artifactory.apps.xnkpeyx0.canadacentral.aroapp.io/gitops-local/eventbrokersink
  tag: latest
imagePullSecrets: artifactory-secret
name: event-broker-sink
replicaCount: 1
resources: {}
route:
  kind: Service
  targetPort: 8080-tcp
  termination: edge
  weight: 100
service:
  port: 8080
  type: ClusterIP
solace:
  host: pubsubplus-openshift-cris-pubsubplus-openshift.gitops-kustomize.svc.cluster.local
  topic: test/topic
  username: test
storage:
  url: http://json-storage:8080

HOOKS:
MANIFEST:
---
# Source: eventBrokerSink/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "ew0KICAgICJhdXRocyI6ew0KICAgICAgICAiYXJ0aWZhY3RvcnktYXJ0aWZhY3RvcnkuYXBwcy54bmtwZXl4MC5jYW5hZGFjZW50cmFsLmFyb2FwcC5pbyI6ew0KICAgICAgICAgICAgInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IkFkbWluMTIzISIsImF1dGgiOiJZV1J0YVc0NlFXUnRhVzR4TWpNaCIsImVtYWlsIjoiIg0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0NCn0="
---
# Source: eventBrokerSink/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: solace-config
data:
  host: pubsubplus-openshift-cris-pubsubplus-openshift.gitops-kustomize.svc.cluster.local
  username: test
  topic: test/topic
---
# Source: eventBrokerSink/templates/storage-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config
data:
  url: http://json-storage:8080
---
# Source: eventBrokerSink/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: event-broker-sink
  labels:
    app: event-broker-sink
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: event-broker-sink
---
# Source: eventBrokerSink/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-broker-sink
  labels:
    app: event-broker-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-broker-sink
  template:
    metadata:
      labels:
        app: event-broker-sink
    spec:
      imagePullSecrets:
      - name: artifactory-secret
      containers:
        - name: event-broker-sink
          image: "artifactory-artifactory.apps.xnkpeyx0.canadacentral.aroapp.io/gitops-local/eventbrokersink:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: host
          - name: USERNAME
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: username
          - name: TOPIC
            valueFrom:
              configMapKeyRef:
                name: solace-config
                key: topic
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: storage-config
                key: url
          resources: {}
---
# Source: eventBrokerSink/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: event-broker-sink
spec:
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: event-broker-sink
    weight: 100

