# Default values for eventBrokerSink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: event-broker-sink

replicaCount: 1

image:
  repository: artifactory-artifactory.apps.xnkpeyx0.canadacentral.aroapp.io/gitops-local/eventbrokersink
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: artifactory-secret


service:
  type: ClusterIP
  port: 8080

route:
  targetPort: 8080-tcp
  termination: edge
  kind: Service
  weight: 100


resources: {}

solace:
  host: solace-pubsubplus-openshift-dev
  username: test
  topic: test/topic

storage:
  url: http://json-storage:8080
