apiVersion: v2
name: event-broker-poc
description: A Parent Helm chart to deploy event-broker-poc's components 
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: eventBrokerSource
    version: ~0.1.0
    repository: "https://raw.githubusercontent.com/danialasghar/GitOps-PoC/main/eventBrokerSource/helm/package"
  - name: eventBrokerSink
    version: ~0.1.0
    repository: "https://raw.githubusercontent.com/danialasghar/GitOps-PoC/main/eventBrokerSink/helm/package"
  - name: pubsubplus-openshift-dev
    version: ~3.1.0
    repository: "https://raw.githubusercontent.com/danialasghar/GitOps-PoC/main/solace/helm"

